#pragma once

enum networking_status {
	NETWORK_INACTIVE,
	NETWORK_CONNECTING, 
	NETWORK_CONNECTED,

};

enum networker_message {
	NETWORKER_MESSAGE_NULL_MESSAGE,
	NETWORKER_MESSAGE_CONNECTING,
	NETWORKER_MESSAGE_CONNECTION_FAILED,
	NETWORKER_MESSAGE_AUTHENTICATING,
	NETWORKER_MESSAGE_WRONG_PASSWORD,
	NETWORKER_MESSAGE_NOT_AUTHORIZED,
	NETWORKER_MESSAGE_SERVER_FULL,
	NETWORKER_MESSAGE_CONNECTED,
	NETWORKER_MESSAGE_DISCONNECTED,
	NETWORKER_MESSAGE_CONNECTION_LOST,
};

enum networker_request_type {
	NULL_REQUEST,
	CONNECT_TO_SERVER, 
	DISCONNECT_FROM_SERVER,
	SEND_GAME_PACKET,
};

struct game_client;

void init_networker(struct game_client* game);

void networker_thread(struct game_client* game);