#pragma once

#ifndef RESOURCES_H
#define RESOURCES_H

static const int RESOURCE_PIXEL_FONT_DEFAULT = 0;
static const int RESOURCE_PIXEL_FONT_DEBUG = 1;
static const int RESOURCE_TEXTURE_DIRT_MULTIBLE = 10;
static const int RESOURCE_TEXTURE_MENU_BUTTON = 11;
static const int RESOURCE_TEXTURE_MENU_BUTTON_HOVER = 12;
static const int RESOURCE_TEXTURE_MENU_DISABLED = 13;

static const int RESOURCE_TEXTURE_MENU_BUTTON_SHORT = 14;
static const int RESOURCE_TEXTURE_MENU_BUTTON_HOVER_SHORT = 15;

#endif // !RESOURCES_H
